# Dependencies
markdown: kramdown
highlighter: rouge

# Gems
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-seo-tag

# Settings
color: '#fab005'
exclude:
  [
    CNAME,
    README.md,
    NOTES.md,
    LICENSE.md,
    .gitignore,
    package.json,
    _js,
    _scss,
    _images,
    gulpfile.js,
    gulpconfig.js,
    node_modules,
    gemfile,
    Gemfile.lock,
  ]
permalink: /:title/
compress_html:
  clippings: all
  comments: all
dark_theme: false

# Site meta
title: Summer
tagline: 'Delicious & healthy recipes'
description: 'A simple Jekyll theme with a photo sidebar.'
keywords: 'connor, b√§r, designer, traveller, code, jekyll, developer, theme'
url: "http://www.lostauthenticrecipes.com"
baseurl: ""
assets: /assets
images: /images/
image: index-large.jpg
logo: /assets/icons/apple-icon-144x144.png

author:
  name: Soumya Shubhra Ghosh
  bio:
  image: author
  url: https://connorbaer.co
  email: hello@connorbaer.co
  twitter: connor_baer

social:
  twitter: https://twitter.com/lostauthenticrecipes
  instagram: https://instagram.com/lostauthenticrecipes
  facebook: https://facebook.com/lostauthenticrecipes

version: 2.0.0

github:
  repo: https://github.com/connectsoumya/lostrecipes

# Integrations
# typekit:              fcv7rfe

google_fonts:
  Overpass: 400, 600, 800

# google_analytics_key: UA-37412525-4
# google_site_verification: Z-pc_HPc4XNBz8xg1fgtxO2MSIYLirZc2jWTNq0bJyM

# Content
excerpt_separator: <!-- Read more -->

navigation:
  GitHub: https://github.com/connor-baer/summer
  Download: https://github.com/connor-baer/summer/archive/gh-pages.zip

collections:
  recipes:
    output: true

defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      lang: en
      permalink: /news/:title/
  - scope:
      path: ''
      type: recipes
    values:
      layout: recipe
      lang: en
      permalink: /:title/
